### ISSUE TITLE
Unseal failing

### ISSUE THREAD

**Issue by b-carr** [NationalSecurityAgency/kmyth#12]
Attempting to unseal a ski file gives an error:
```
$ ./kmyth-unseal -i out.ski -o out
kmyth-0.0.0 INFO - src/util/tpm2_config_tools.c(tpm2_init_connection:82) initialized connection to TPM 2.0 emulator
kmyth-0.0.0 ERROR - src/util/tpm2_kmyth_io.c(kmyth_getSkiBlock:929) unexpected delimiter ... exiting
kmyth-0.0.0 ERROR - src/util/tpm2_kmyth_io.c(tpm2_kmyth_read_ski_file:510) get PCR selection list error ... exiting
kmyth-0.0.0 ERROR - src/util/tpm2_kmyth_seal.c(tpm2_kmyth_unseal:402) error reading .ski file out.ski ... exiting
kmyth-0.0.0 ERROR - src/unseal/main.c(main:136) kmyth-unseal failed ... exiting

```

**Comment by bit-bender** [comment]
I haven't been able to re-create that error, but it looks like the delimiter for the "PCR Selection List" in the .ski file is not what is expected ("-----PCR SELECTION LIST-----\n"). Is there anything weird with the "Original Filename" block preceding it? Is out.ski clearly corrupted (e.g., kmyth-seal did not produce it correctly) or is something else going on?

**Comment by b-carr** [comment]
I've done some more digging, it's caused by having a `-` in the original filename. We detect the start of the next ski block by looking for a `-`, so if there's one in the original filename it thinks that's where the next block starts. I'll give some thought to how I think we should handle it, but I'm open to suggestions too.

**Comment by b-carr** [comment]
Ok, here's what I want to do, feel free to talk me out of it. I think we should re-do the file parsing to step between newlines (rather than stopping when it hits a `-`). Once it hits a newline it looks back to the character after the previous newline and checks if the string in between is the expected delimiter. If it is, process the ski block, if it isn't throw an error.

I think we can accomplish this fairly easily using one or two extra pointers to track positions in the `contents` array, but I also expect it will be tricky to get exactly right.

**Comment by b-carr** [comment]
Turns out it could be done more simply than I originally thought.
