### ISSUE TITLE
Investigate ECDH session key generation in a single step

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#146]
The compute_ecdh_shared_secret() function in sgx/common/src/ecdh_utils.c uses OpenSSL's ECDH_compute_key() call to produce a 'shared secret' result. The last parameter seems to allow the specification of a KDF. This might, therefore, support direct use of this result as a "session key", instead of a two-step (compute ECDH shared secret and then use shared secret to compute session key) approach.

**Comment by b-carr** [comment]
Is this issue still relevant? Looking at the code today it looks like it uses ```EVP_PKEY_derive``` which doesn't have a place to drop in a KDF.

**Comment by bit-bender** [comment]
Yes, this issue is no longer relevant. Closing for that reason.

**Comment by bit-bender** [comment]
Changed reason for closure from "completed" to "not planned."
