### ISSUE TITLE
Clean up error handling and memory management

### ISSUE THREAD

**Issue by b-carr** [NationalSecurityAgency/kmyth#25]
There are quite a few places in the code where memory isn't freed on failure, or where failure conditions aren't properly handled. We need to go through the entire codebase ensuring all errors are handling appropriately and all memory is freed appropriately.

**Comment by wmillstone** [comment]
It looks like even when memory is freed, the freed pointer is not usually set to NULL. While not necessary, doing after a call to free() would prevent errors if the code ever attempts to free the same memory more than once.

**Comment by PeterHamilton** [comment]
> It looks like even when memory is freed, the freed pointer is not usually set to NULL. While not necessary, doing this after a call to free() would prevent errors if the code ever attempts to free the same memory more than once. In most cases, this is a non-issue, but there are a few function calls that do some memory management in the background that isn't always obvious (for example `tpm2_kmyth_unseal()` in `tpm2_kmyth_seal.c`) and this would protect us against unseen errors.

Yep, I have more updates that explicitly set freed pointers to NULL for just this reason. Hoping I can get those out soon.
