### ISSUE TITLE
Rename default branch

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#33]
We will be re-naming our default branch from master to main. GitHub has published [guidance](https://github.com/github/renaming) on this topic.

New tools have been promised to make this more seamless, but, in our case, we should be in pretty good shape to go ahead and switch over. For instance, as of July 17, 2020, [links to deleted branched will now automatically redirect to the default branch](https://github.blog/changelog/2020-07-17-links-to-deleted-branches-now-redirect-to-the-default-branch/). The biggest challenge looks to be the current need to manually re-target open pull requests to the new default branch. For this reason, we may schedule the change for either a time in the near future when this is minimized (e.g., no or few open pull requests) or when the promised automated tooling becomes available to deal with this.

**Comment by PircDef** [comment]
I'll wait to create any more pull requests until after this is done.

**Comment by bit-bender** [comment]
This rename has now been performed. If you experience any issues or require any assistance related to this transition, please leave a comment.
