### ISSUE TITLE
Consistent Authorization String Handling

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#35]
The kmyth applications accept as command line parameters an authorization password (used to create a hash used as an authorization value in a TPM policy) and a password for the TPM owner (storage) hierarchy. They are currently initialized differently. The authString variable is initialized to a NULL pointer and the ownerAuthPasswd variable is initialized to an empty string. This issue proposes to standardize on the approach where we initialize to the NULL pointer and then use a check for NULL and set to a default value, where required.

**Comment by wmillstone** [comment]
What are the advantages of standardizing to initialize to NULL instead of standardizing to initialize to the empty string? Initializing to NULL requires us to write more checks for NULL before clearing the variables, since strlen(NULL) results in an error.

**Comment by b-carr** [comment]
My preference is to initialize to NULL and explicitly capture the length when reading off the command line. I think that fits more naturally with the API Nick is working to.

**Comment by PircDef** [comment]
Is this issue completed? I think this may have been done somewhere between #37 and #45
