### ISSUE TITLE
Create Kmyth Parameter Struct

### ISSUE THREAD

**Issue by PircDef** [NationalSecurityAgency/kmyth#38]
The auth_string, pcrs_string, owner_auth_password, and cipher_string are passed in and out of several calls. These should be consolidated into a single struct to be passed in and out of tpm2_kmyth_seal and tpm2_kmyth_unseal

**Comment by b-carr** [comment]
I've been sort of wresting with the best way to do this all day, and I'm no longer sure a single structure is the right call from an API perspective. Does it make more sense to expose all the struct and all the support code through the API, or to have the API use standard types? We could still build the struct internally if it's helpful, but looking at `tpm2_kmyth_seal` and `tpm2_kmyth_unseal` it's not clear to me that there's a big advantage there.

**Comment by PircDef** [comment]
I think this is mostly addressed in PR #45. Once that is resolved, I think we can close this.
