### ISSUE TITLE
Restructure build using recursive makefiles

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#4]
As a step to make the code and build process more modular and portable, it will probably help to revamp the current single, top-level makefile approach by instead applying a hierarchical (recursive) makefile schema.

**Comment by b-carr** [comment]
As part of this we should add build flags to turn on/off optional features. The only one I have immediately in mind is the KMIP `getkey`. We should be able to build against any (or all) available `getkey` backends but if the user doesn't want a particular backend we shouldn't require it be present just to build others.

**Comment by bit-bender** [comment]
Although we went a different direction (e.g., a centralized Makefile), pull request #24 reworked and improved the build process. Therefore, I am closing this general "make the build process more modular and portable" issue with the expectation that any further necessary refinements to the build process will be covered by new and more specific issues.
