### ISSUE TITLE
Add unit tests for kmyth TLS utilities

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#68]
Currently, for the kmyth functionality implemented in tpm2/src/util/tls_util.c, the only unit tests that have been written are some simple checks for invalid inputs to tls_set_context(). Additional unit tests, therefore, must be written and integrated into the kmyth unit testing framework for the TLS utility functions found in tpm2/src/util/tls_util.c.

**Comment by PeterHamilton** [comment]
I'll add a few more unit tests for `tls_util.c`, primarily just checking input argument error handling for a few functions.

We probably need to decide on a good function/API mocking framework if we want to fully test functions that call OpenSSL or TPM-related functions.
