### ISSUE TITLE
Add unit tests for kmyth seal application

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#79]
Unit tests must be written and integrated into the kmyth unit testing framework for the top-level (main()) implementation of the TPM 2.0 based kmyth-seal application in tpm2/src/main/seal.c.

**Comment by b-carr** [comment]
I'm not sure there's anything to unit test here. The only functionality not implemented in `main` is the PCR string parsing, but that's entirely specific to the example seal executable.

**Comment by PircDef** [comment]
I agree with @b-carr. This is better served by integration tests than unit tests. The PCR string parsing is tested elsewhere.
