### ISSUE TITLE
Add unit tests for kmyth unseal application

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#80]
Unit tests must be written and integrated into the kmyth unit testing framework for the top-level (main()) implementation of the TPM 2.0 based kmyth-unseal application in tpm2/src/main/unseal.c.

**Comment by b-carr** [comment]
I don't think there's anything to unit test for unseal. All the functionality is implemented in main, so we'd have to just call the executable to test anything.

**Comment by PircDef** [comment]
I agree with @b-carr. This type of test is best suited for integration testing.
