### ISSUE TITLE
Add unit tests for kmyth getkey application

### ISSUE THREAD

**Issue by bit-bender** [NationalSecurityAgency/kmyth#81]
Unit tests must be written and integrated into the kmyth unit testing framework for the top-level (main()) implementation of the TPM 2.0 based kmyth-getkey application in tpm2/src/main/getkey.c.

**Comment by b-carr** [comment]
I don't think there's anything to unit test here. The only functionality that's not contained in main is `check_string_arg`. While we could write tests for it I'm not sure it really buys us anything.

**Comment by PircDef** [comment]
I agree with @b-carr. This test is a little different from seal/unseal because of the TLS connection, but it is best suited for a different testing framework.
